# .gitlab-ci.yml extension enables completion support in IntelliJ

deploy:foreach:
  stage: deploy
  variables:
    TZ: "UTC" # Generally recommended for reproducible builds, and we're skipping tests in this job anyway.
  before_script:
    - apt-get update
    - apt-get -y install gpg
    - gpg --pinentry-mode loopback --passphrase $ACROSS_GPG_PASSPHRASE --import $ACROSS_GPG_PRIVATE_KEY
    - gpg --list-keys
  script:
    # For reproducible builds, we have to run the build twice:
    - mvn $MAVEN_CLI_OPTS clean install -DskipTests
    - mvn $MAVEN_CLI_OPTS clean verify artifact:compare -DskipTests
    - mvn $MAVEN_CLI_OPTS --settings ci_settings.xml --activate-profiles deploy,across deploy -DskipTests
#  only:
#    variables:
#      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#

# TODO: on push of a tag, run a deploy to Sonatype
# Disadvantage is that that will run all integration tests again, unless we want disable those on a tag push
